### ISSUE TITLE
Error when running `ng build -c production` on a project using this package

### ISSUE THREAD

**Issue by ipabz** [Marcelh1983/angular-document-viewer#10]
Here's the error:

ERROR in ./node_modules/ngx-doc-viewer/fesm2015/ngx-doc-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/icpabelona/Projects/CSPreston/rap-2.0-web/node_modules/typescript/lib/typescript.js:16599:21)

My Angular Version:

Angular CLI: 8.3.13
Node: 10.15.3
OS: darwin x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.3.13
@angular/cdk                      7.3.7
@angular/cli                      8.3.13
@ngtools/webpack                  8.1.3
@schematics/angular               8.3.13
@schematics/update                0.803.13
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.35.2

**Comment by Marcelh1983** [comment]
Thanks for reporting. Upgrading typescript to 3.5.3 will fix it. But I'll try to find out if it can be fixed in the packages as well.

**Comment by ipabz** [comment]
> Thanks for reporting. Upgrading typescript to 3.5.3 will fix it. But I'll try to find out if it can be fixed in the packages as well.

Thank you for your reply. Will try to upgrade typescript.

**Comment by ipabz** [comment]
Updating typescript to 3.5.3 doesn't seem to solve it. I'm getting the same error.

Angular CLI: 8.3.13
Node: 10.15.3
OS: darwin x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.3.13
@angular/cdk                      7.3.7
@angular/cli                      8.3.13
@ngtools/webpack                  8.1.3
@schematics/angular               8.3.13
@schematics/update                0.803.13
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.35.2

**Comment by Marcelh1983** [comment]
I can reproduce this on an old repository. The error disappeared after running:

`ng upgrade @angular/cli`

But it's a weird issue and it's not clear to me what is causing the error. If you can't get it working with the latest than you can install ngx-doc-viewer@0.1.20

Here issues describing the same problem:
https://github.com/angular/angular-cli/issues/13172
https://github.com/KillerCodeMonkey/ngx-quill/issues/573

So if someone else knows what causes it and how it can be solved, please let me know 🙏

**Comment by ipabz** [comment]
> I can reproduce this on an old repository. The error disappeared after running:
> 
> `ng upgrade @angular/cli`
> 
> But it's a weird issue and it's not clear to me what is causing the error. If you can't get it working with the latest than you can install ngx-doc-viewer@0.1.20
> 
> Here issues describing the same problem:
> [angular/angular-cli#13172](https://github.com/angular/angular-cli/issues/13172)
> [KillerCodeMonkey/ngx-quill#573](https://github.com/KillerCodeMonkey/ngx-quill/issues/573)
> 
> So if someone else knows what causes it and how it can be solved, please let me know 🙏

got it to work by running `ng update @angular/cli`

thanks @Marcelh1983 :-)
