### ISSUE TITLE
Version 0.1.21 Possibly not compatible with Angular 8?

### ISSUE THREAD

**Issue by SGissubel** [Marcelh1983/angular-document-viewer#15]
Installing & using the package. Worked fine.

I ran a build - and the build failed
Received the following errors: 

```
ERROR in ./node_modules/ngx-doc-viewer/fesm2015/ngx-doc-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/....Web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/....Web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/....Web/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/....Web/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/....Web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/....Web/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/....Web/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/....Web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/....Web/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/....Web/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/....Web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/....Web/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/....Web/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/....Web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/....Web/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/....Web/node_modules/typescript/lib/typescript.js:16599:21)
```

I uninstalled & installed 0.1.20 - and the build worked.

**Comment by SGissubel** [comment]
Even though this built the other day - 0.1.20 is also now failing with the same error `Cannot read property 'kind' of undefined`

**Comment by Marcelh1983** [comment]
Hi @SGissubel, thanks for reporting. it's related to issue #10. Upgrading the angular/cli seems to solve the problem. I tried to find out what causes the error for older angular/cli versions but I couldn't find a solution. If someone else can point me to the right direction I will do another attempt to fix it

**Comment by Marcelh1983** [comment]
version 0.1.19 works with older @angular-cli versions

**Comment by SGissubel** [comment]
Thanks @Marcelh1983  - I will use 0.1.19 for now. The project I am working on is time sensitive - and updated cli at the moment is not an option. But hopefully when possible, I will update the cli & attempt to update the ngx-doc-viewer version as well. Thanks for you assistance
