### ISSUE TITLE
ERROR in ./node_modules/ngx-doc-viewer/fesm5/ngx-doc-viewer.js

### ISSUE THREAD

**Issue by Appuhamy** [Marcelh1983/angular-document-viewer#20]
ERROR in ./node_modules/ngx-doc-viewer/fesm5/ngx-doc-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:230:35)
    at checkNodeForDecorators (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:53:21)
    at visitNodes (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\typescript\lib\typescript.js:16857:24)
    at checkNodeForDecorators (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\typescript\lib\typescript.js:16752:21)
    at checkNodeForDecorators (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\typescript\lib\typescript.js:16809:24)
    at checkNodeForDecorators (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (D:\PROJECTS\DWF\SAAS\UI\SaaS-web\saas-web\node_modules\typescript\lib\typescript.js:16622:24)

**Comment by Appuhamy** [comment]
"ngx-doc-viewer": "^0.1.25",

**Comment by Marcelh1983** [comment]
Hi @Appuhamy see #10 updating the cli: `ng upgrade @angular/cli` (and also @angular-devkit/build-angular) solves this problem. If this is not an option for your project then use version 0.1.19.

**Comment by Appuhamy** [comment]
Thank You for the help its working now @Marcelh1983 !!!
