### ISSUE TITLE
Method Not Implemented

### ISSUE THREAD

**Issue by ArmandoPerdomo** [Marcelh1983/angular-document-viewer#47]
After installing, importing and implementing [https://www.npmjs.com/package/ngx-doc-viewer#url](this) for external document view, I get this error

```
client:159 Error: Method not implemented.
    at AstTranslator.visitQuote (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:212:69)
    at Quote.visit (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:7394:28)
    at AstTranslator.translate (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:73:24)
    at Object.astToTypescript (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:50:27)
    at TcbExpressionTranslator.translate (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1206:33)
    at tcbExpression (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1194:27)
    at processAttribute (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1466:24)
    at Array.forEach (<anonymous>)
    at tcbGetDirectiveInputs (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1416:19)
    at TcbDirectiveOp.execute (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:340:26)
    at Scope.executeOp (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:969:26)
    at Scope.render (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:882:22)
    at Object.generateTypeCheckBlock (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:56:37)
    at TypeCheckFile.addTypeCheckBlock (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_file.js:45:41)
    at TypeCheckContext.addTemplate (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\context.js:109:36)
    at ComponentDecoratorHandler.typeCheck (C:\Armando\Proyectos\SecureDocumentViewer\secure-document-viewer-webapp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:378:17)`
```

This only happends when I invoke the selector `<ngx-doc-viewer>`

```
<ngx-doc-viewer
        [url]="http://docs.google.com/fileview?id=0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh"
        viewer="url" style="width:100%;height:50vh;">
    </ngx-doc-viewer>
```

am I missing something?

**Comment by ArmandoPerdomo** [comment]
This are my package.json dependencies

`"dependencies": {
    "@angular/animations": "~9.0.0",
    "@angular/cdk": "^9.1.3",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.0.0",
    "@angular/material": "^9.1.3",
    "@angular/material-moment-adapter": "^9.2.1",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
    "bootstrap": "^4.4.1",
    "moment": "^2.24.0",
    "ngx-auth": "^5.3.0",
    "ngx-doc-viewer": "^1.1.0",
    "ngx-filesize": "^2.0.15",
    "ngx-loading": "^8.0.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "~9.0.1",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }`

**Comment by ArmandoPerdomo** [comment]
Is a angular compilation error, [url] recieve a string parameter, just add single quotes to the url from this

`[url]="http://docs.google.com/fileview?id=0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh"`

to this

`[url]="'http://docs.google.com/fileview?id=0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh'"`

I will mark as close

```
<ngx-doc-viewer
        [url]="'http://docs.google.com/fileview?id=0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh'"
        viewer="url" style="width:100%;height:50vh;">
</ngx-doc-viewer>
```
