### ISSUE TITLE
after npm install the , HTML cannot find the <ngx-doc-viewer>

### ISSUE THREAD

**Issue by dora61** [Marcelh1983/angular-document-viewer#52]
I import NgxDocViewerComponent into my code as below:
TS:
  import { NgxDocViewerComponent } from 'ngx-doc-viewer'

HTML:
      <ngx-doc-viewer
        [url]="https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_10.xlsx"
        viewer="google"
        style="width:100%;height:50vh;">
      </ngx-doc-viewer>

But when I start my app , there come's a error like below:
should I missed something for the ngx-doc-viewer?

ERROR in Error: Method not implemented.
    at AstTranslator.visitQuote (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:225:19)
    at Quote.visit (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler\bundles\compiler.umd.js:7710:28)
    at AstTranslator.translate (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:73:24)
    at Object.astToTypescript (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:50:27)
    at TcbExpressionTranslator.translate (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1212:33)
    at tcbExpression (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1200:27)
    at processAttribute (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1474:24)
    at Array.forEach (<anonymous>)
    at tcbGetDirectiveInputs (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1424:19)
    at TcbDirectiveOp.execute (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:342:26)
    at Scope.executeOp (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:975:26)
    at Scope.render (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:888:22)
    at Object.generateTypeCheckBlock (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:56:37)
    at TypeCheckFile.addTypeCheckBlock (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_file.js:45:41)
    at TypeCheckContext.addTemplate (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\context.js:109:36)
    at ComponentDecoratorHandler.typeCheck (C:\pleiades\workspace_front\financeinfo\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:379:17)

**Comment by Marcelh1983** [comment]
HI @dora61 , 
`[url]="https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_10.xlsx"` should be changed to `url="https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_10.xlsx"` or `[url]="'https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_10.xlsx'"`

Could that be the problem?
